#!/usr/bin/env bash

set -euo pipefail

root=`dirname "$0"`
root=`realpath "$root"`

. "$root/../node_modules/faucet-pipeline/test/cli_harness.sh"

begin "$root/test_transpilation"
	faucet
	assert_identical "./dist/bundle.js" "./expected.js"
end

echo; echo "SUCCESS: all tests passed"
